apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-dev
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.13
    helm:
        values: |
          tolerations:
            - key: service
              value: app
              effect: NoSchedule
            - key: kubernetes.azure.com/scalesetpriority
              value: spot
              effect: NoSchedule
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true