apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.22.0
    helm:
      values: |
        pushgateway:
          enabled: false
        kube-state-metrics:
          ## If false, kube-state-metrics sub-chart will not be installed
          ##
          enabled: false
        crds:
          enabled: false
        #prometheusOperator:
        #  enabled: true
        #  admissionWebhooks:
        #    enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
