apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-operator-crds
    targetRevision: 6.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
