apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-demo
  labels:
    app: todos-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-demo
  template:
    metadata:
      labels:
        app: todos-demo
    spec:
      containers:
        - name: todos
          image: alfredocoj/api-rest-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /todos
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
